ALTER TABLE KNOWN_FINDINGS
    ALTER COLUMN ide_relative_file_path SET DATA TYPE VARCHAR;
ALTER TABLE SERVER_FINDINGS
    ALTER COLUMN file_path SET DATA TYPE VARCHAR;
ALTER TABLE LOCAL_ONLY_ISSUES
    ALTER COLUMN server_relative_path SET DATA TYPE VARCHAR;
