name: Releasability Status
on:
    workflow_run:
        workflows: [ "Build" ]  # Name must match the name of the build workflow
        types: [ completed ]
        branches:
            - master
            - branch-*

jobs:
    releasability-status:
        name: Releasability status
        runs-on: sonar-xs-public
        permissions:
            id-token: write
            statuses: write
            contents: read
        if: github.event.workflow_run.conclusion == 'success'
        steps:
            -   uses: SonarSource/gh-action_releasability/releasability-status@683b9a1ffd08c3a23af1d1bffb67a9d7bcfb1b08 # 3.0.4
                with:
                    optional_checks: "Jira"
                env:
                    GITHUB_TOKEN: ${{ github.token }}
