name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  CACHE_BACKEND: s3

jobs:
  scan:
    runs-on: sonar-m
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: 2026.4.11
      - name: Install dotnet for Omnisharp tests
        run: |
          mise use dotnet@8
      - uses: SonarSource/ci-github-actions/build-maven@de29c54be07c772c6afc381db8ae4bfcbfe4df12 # 1.8.0 # dogfood
        with:
          maven-args: -Dcommercial -Dsonar.coverage.jacoco.xmlReportPaths=${{ github.workspace }}/report-aggregate/target/site/jacoco-aggregate/jacoco.xml
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          scanner-java-opts: '-Xmx2g'
      - name: Upload failure diagnostics
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: shadow-scans-test-report
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
      - name: Run IRIS sync
        uses: SonarSource/unified-dogfooding-actions/run-iris@03e023516511b1c9da325ad104c2290e3b91688c # 1.1.0
        with:
          primary_project_key: "org.sonarsource.sonarlint.core:sonarlint-core-parent"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.sonarlint.core:sonarlint-core-parent"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.sonarlint.core:sonarlint-core-parent"
          shadow2_platform: "SQC-US"
